### ISSUE TITLE
Some tests not passed

### ISSUE THREAD

**Issue by tim77** [tmerr/i3ipc-rs#48]
Maybe we can fix this somehow?

```rust
running 19 tests
test test::connect ... FAILED
test test::from_str_barconfig ... ok
test test::from_str_binding_event ... ok
test test::event_subscribe ... FAILED
test test::from_str_window ... ok
test test::from_str_mode ... ok
test test::from_str_workspace ... ok
test test::get_bar_ids ... FAILED
test test::get_marks ... FAILED
test test::get_outputs ... FAILED
test test::get_bar_ids_and_one_config ... FAILED
test test::get_version ... FAILED
test test::get_workspaces ... FAILED
test test::from_str_output ... ok
test test::run_command_fail ... FAILED
test test::run_command_nothing ... FAILED
test test::run_command_multiple_success ... FAILED
test test::get_tree ... FAILED
test test::run_command_single_sucess ... FAILED
failures:
---- test::connect stdout ----
thread 'test::connect' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- test::event_subscribe stdout ----
thread 'test::event_subscribe' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_bar_ids stdout ----
thread 'test::get_bar_ids' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_marks stdout ----
thread 'test::get_marks' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_outputs stdout ----
thread 'test::get_outputs' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_bar_ids_and_one_config stdout ----
thread 'test::get_bar_ids_and_one_config' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_version stdout ----
thread 'test::get_version' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_workspaces stdout ----
thread 'test::get_workspaces' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::run_command_fail stdout ----
thread 'test::run_command_fail' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::run_command_nothing stdout ----
thread 'test::run_command_nothing' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::run_command_multiple_success stdout ----
thread 'test::run_command_multiple_success' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::get_tree stdout ----
thread 'test::get_tree' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
---- test::run_command_single_sucess stdout ----
thread 'test::run_command_single_sucess' panicked at 'called `Result::unwrap()` on an `Err` value: GetSocketPathError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
failures:
    test::connect
    test::event_subscribe
    test::get_bar_ids
    test::get_bar_ids_and_one_config
    test::get_marks
    test::get_outputs
    test::get_tree
    test::get_version
    test::get_workspaces
    test::run_command_fail
    test::run_command_multiple_success
    test::run_command_nothing
    test::run_command_single_sucess
test result: FAILED. 6 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by tmerr** [comment]
Is i3 running? The tests depend on it. It sounds like it's failing around here https://github.com/tmerr/i3ipc-rs/blob/master/src/lib.rs#L108-L132

**Comment by tim77** [comment]
> Is i3 running?

Not sure is this possible to run it in systemd-nspawn container which [mock](https://github.com/rpm-software-management/mock/wiki) using? I am trying to build i3ipc-rs for official Fedora repos. Here is [full build log](https://copr-be.cloud.fedoraproject.org/results/atim/rust-crates/fedora-rawhide-x86_64/01111597-rust-i3ipc/builder-live.log.gz), maybe this can help.
